In [1]:
import tensorflow as tf 
from tensorflow.keras.models import load_model 
import pickle 
import pandas as pd 
import numpy as np

In [2]:
model = load_model('model.h5')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [3]:
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [4]:
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder = pickle.load(file)

with open('onehot_encoder_gender.pkl','rb') as file:
    onehot_encoder = pickle.load(file)

with open('scalar.pkl','rb') as file:
    scalar = pickle.load(file)

In [7]:
input_data['Gender'] = label_encoder.transform([input_data['Gender']])

In [9]:
df = pd.DataFrame(input_data)

In [10]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [17]:
data = onehot_encoder.transform([[input_data['Geography']]])
df = pd.concat([df,pd.DataFrame(data,columns=onehot_encoder.get_feature_names_out())],axis=1)

c:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [18]:
df.drop('Geography',axis=1,inplace=True)

In [19]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [21]:
df_scaled = scalar.transform(df)

In [23]:
predicted_value = model.predict(df_scaled)
print(predicted_value[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
[0.08023658]